version: '3.1'
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_SSL_CERTFILE: "${RABBITMQ_SERVER_CERT}"
      RABBITMQ_SSL_KEYFILE: "${RABBITMQ_SERVER_KEY}"
      RABBITMQ_SSL_CACERTFILE: "${RABBITMQ_CA_CERT}"
      RABBITMQ_MANAGEMENT_SSL_CERTFILE: "${RABBITMQ_SERVER_CERT}"
      RABBITMQ_MANAGEMENT_SSL_KEYFILE: "${RABBITMQ_SERVER_KEY}"
      RABBITMQ_MANAGEMENT_SSL_CACERTFILE: "${RABBITMQ_CA_CERT}"
    expose:
      - "15671"
      - "5671"
    network_mode: "host"
    volumes:
      - './certs/rabbitmq:/cert_rabbitmq'
networks:
  lb7_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: '${NETWORK_SUBNET}'